package managers;

import java.io.InputStream;
import java.io.PrintStream;
import java.util.Map;
import java.util.Scanner;
import java.util.function.Consumer;

public class DBManager {
    private PrintStream out;
    private Scanner in;
    private final Map<String, Consumer<String>> functions =  Map.of(
        "/add", DBManager.this::add,
        "/delete", DBManager.this::delete,
        "/show_all", DBManager.this::showAll,
        "/price", DBManager.this::price,
        "/change_price", DBManager.this::changePrice,
        "/filter_by_price", DBManager.this::filterByPrice
    );

    public DBManager() {
        out = System.out;
        in = new Scanner(System.in);
    }

    public DBManager(InputStream in, PrintStream out) {
        this.out = out;
        this.in = new Scanner(in);
    }

    public void start() {
        out.println("Please type your database login: ");
        String login = in.next();
        out.println("Please type your database password: ");
        String password = in.next();
        out.println("Please type number of autogenerated rows: ");
        int autogenerate = in.nextInt();
        while (in.hasNextLine()) {
            try {
                String command = in.next();
                if (command.equals("/exit")) {
                    break;
                }
                execute(command + in.nextLine());
            } catch (Exception e) {
                e.printStackTrace();
                out.println("Error : " + e.getMessage());
            }
        }
    }

    public void execute(String commandLine) {
        Scanner line = new Scanner(commandLine);

        if (line.hasNextLine()) {
            functions.getOrDefault(line.next(), (c) -> out.println("No such command")).accept(line.nextLine().trim());
        }
    }

    private void add(String args) {
        out.println("add");
    }

    private void delete(String args) {
        out.println("delete");
    }

    private void showAll(String args) {
        out.println("showAll");
    }

    private void price(String args) {
        out.println("price");
    }

    private void changePrice(String args) {
        out.println("changePrice");
    }

    private void filterByPrice(String args) {
        out.print("filterByPrice");
    }
}
